//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"|DataDirectory|\\Base de Dato" +
            "s Software.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string Base_de_Datos_SoftwareConnectionString {
            get {
                return ((string)(this["Base_de_Datos_SoftwareConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-D66FKKU\\DANGELMSSQL;Initial Catalog=\"Base de Datos Software\";" +
            "Integrated Security=True")]
        public string Base_de_Datos_SoftwareConnectionString1 {
            get {
                return ((string)(this["Base_de_Datos_SoftwareConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-D66FKKU\\DANGELMSSQL;Initial Catalog=Base_de_Datos_Software2;I" +
            "ntegrated Security=True")]
        public string Base_de_Datos_Software2ConnectionString {
            get {
                return ((string)(this["Base_de_Datos_Software2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-D66FKKU\\DANGEL;Initial Catalog=Base_de_datos_CONEXION;Persist" +
            " Security Info=True;User ID=sa;Password=dang3l18112007")]
        public string Base_de_datos_CONEXIONConnectionString {
            get {
                return ((string)(this["Base_de_datos_CONEXIONConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-D66FKKU\\DANGELMSSQL;Initial Catalog=\"Base de datos innovatec\"" +
            ";Integrated Security=True")]
        public string Base_de_datos_innovatecConnectionString {
            get {
                return ((string)(this["Base_de_datos_innovatecConnectionString"]));
            }
        }
    }
}
